const SQL_FUNCTION = ["ABS", "ACOS", "ADD_MONTHS", "APPROX_COUNT_DISTINCT", "APPROX_COUNT_DISTINCT_AGG", "APPROX_COUNT_DISTINCT_DETAIL", "APPROX_MEDIAN", "APPROX_PERCENTILE", "APPROX_PERCENTILE_AGG", "APPROX_PERCENTILE_DETAIL", "ASCII", "ASCIISTR", "ASIN", "ATAN", "ATAN2", "AVG", "BFILENAME", "BIN_TO_NUM", "BITAND", "CARDINALITY", "CAST", "CEIL", "CHARTOROWID", "CHR", "CLUSTER_DETAILS", "CLUSTER_DISTANCE", "CLUSTER_ID", "CLUSTER_PROBABILITY", "CLUSTER_SET", "COALESCE", "COLLATION", "COLLECT", "COMPOSE", "CONCAT", "CONVERT", "CON_DBID_TO_ID", "CON_GUID_TO_ID", "CON_ID_TO_DBID", "CON_NAME_TO_ID", "CON_UID_TO_ID", "CORR", "CORR_K", "CORR_S", "COS", "COSH", "COUNT", "COVAR_POP", "COVAR_SAMP", "CUME_DIST", "CURRENT_DATE", "CURRENT_TIMESTAMP", "CV", "DATAOBJ_TO_MAT_PARTITION", "DATAOBJ_TO_PARTITION", "DBTIMEZONE", "DECODE", "DECOMPOSE", "DENSE_RANK", "DEPTH", "DEREF", "DUMP", "EMPTY_BLOB", "EXISTSNODE", "EXP", "EXTRACT", "EXTRACTVALUE", "FEATURE_COMPARE", "FEATURE_DETAILS", "FEATURE_ID", "FEATURE_SET", "FEATURE_VALUE", "FIRST", "FIRST_VALUE", "FLOOR", "FROM_TZ", "GREATEST", "GROUPING", "GROUPING_ID", "GROUP_ID", "HEXTORAW", "INITCAP", "INSTR", "ITERATION_NUMBER", "JSON_ARRAY", "JSON_ARRAYAGG", "JSON_OBJECT", "JSON_OBJECTAGG", "JSON_QUERY", "JSON_SERIALIZE", "JSON_TABLE", "JSON_VALUE", "LAG", "LAST", "LAST_DAY", "LAST_VALUE", "LEAD", "LEAST", "LENGTH", "LISTAGG", "LN", "LNNVL", "LOCALTIMESTAMP", "LOG", "LOWER", "LPAD", "LTRIM", "MAKE_REF", "MAX", "MEDIAN", "MIN", "MOD", "MONTHS_BETWEEN", "NANVL", "NCHR", "NEW_TIME", "NEXT_DAY", "NLSSORT", "NLS_CHARSET_DECL_LEN", "NLS_CHARSET_ID", "NLS_CHARSET_NAME", "NLS_COLLATION_ID", "NLS_COLLATION_NAME", "NLS_INITCAP", "NLS_LOWER", "NLS_UPPER", "NTH_VALUE", "NTILE", "NULLIF", "NUMTODSINTERVAL", "NUMTOYMINTERVAL", "NVL", "NVL2", "ORA_DM_PARTITION_NAME", "ORA_DST_AFFECTED", "ORA_DST_CONVERT", "ORA_DST_ERROR", "ORA_HASH", "ORA_INVOKING_USER",
	"ORA_INVOKING_USERID", "PATH", "PERCENTILE_CONT", "PERCENTILE_DISC", "PERCENT_RANK", "POWER", "POWERMULTISET", "POWERMULTISET_BY_CARDINALITY",
	"PREDICTION", "PREDICTION_BOUNDS", "PREDICTION_COST", "PREDICTION_DETAILS", "PREDICTION_PROBABILITY", "PREDICTION_SET",
	"PRESENTNNV", "PRESENTV", "PREVIOUS", "RANK", "RATIO_TO_REPORT", "RAWTOHEX", "RAWTONHEX", "REF", "REFTOHEX", "REGEXP_COUNT",
	"REGEXP_INSTR", "REGEXP_REPLACE", "REGEXP_SUBSTR", "REGR_AVGX", "REGR_AVGY", "REGR_COUNT", "REGR_INTERCEPT", "REGR_R2", "REGR_SLOPE",
	"REGR_SXX", "REGR_SXY", "REGR_SYY", "REMAINDER", "REPLACE", "ROUND", "ROWIDTOCHAR", "ROWIDTONCHAR", "ROW_NUMBER", "RPAD", "RTRIM", "SESSIONTIMEZONE",
	"SET", "SIGN", "SIN", "SINH", "SOUNDEX", "SQRT", "STANDARD_HASH", "STATS_BINOMIAL_TEST", "STATS_CROSSTAB", "STATS_F_TEST", "STATS_KS_TEST", "STATS_MODE",
	"STATS_MW_TEST", "STATS_ONE_WAY_ANOVA", "STATS_T_TEST_INDEP", "STATS_T_TEST_INDEPU", "STATS_T_TEST_ONE", "STATS_T_TEST_PAIRED", "STATS_WSR_TEST", "STDDEV",
	"STDDEV_POP", "STDDEV_SAMP", "SUBSTR", "SUM", "SYSDATE", "SYSTIMESTAMP", "SYS_CONNECT_BY_PATH", "SYS_CONTEXT", "SYS_DBURIGEN", "SYS_EXTRACT_UTC", "SYS_GUID", "SYS_OP_ZONE_ID", "SYS_TYPEID", "SYS_XMLGEN", "TAN", "TANH", "TO_APPROX_COUNT_DISTINCT", "TO_APPROX_PERCENTILE", "TO_BINARY_DOUBLE", "TO_BINARY_FLOAT", "TO_BLOB", "TO_CHAR", "TO_CLOB", "TO_DATE", "TO_DSINTERVAL", "TO_LOB", "TO_MULTI_BYTE", "TO_NCHAR", "TO_NCLOB", "TO_NUMBER", "TO_SINGLE_BYTE", "TO_TIMESTAMP", "TO_TIMESTAMP_TZ", "TO_YMINTERVAL", "TRANSLATE", "TREAT", "TRIM", "TRUNC", "TZ_OFFSET", "UID", "UNISTR", "UPPER", "USER", "USERENV", "VALIDATE_CONVERSION", "VALUE", "VARIANCE", "VAR_POP", "VAR_SAMP", "VSIZE", "WIDTH_BUCKET", "XMLCAST", "XMLCDATA", "XMLCOLATTVAL", "XMLCOMMENT", "XMLCONCAT", "XMLDIFF", "XMLELEMENT", "XMLEXISTS", "XMLFOREST", "XMLISVALID", "XMLPARSE", "XMLPATCH", "XMLPI", "XMLQUERY", "XMLSERIALIZE", "XMLTABLE", "XMLTRANSFORM"]

const SQL_DATA_TYPES = ["CHAR", "NCHAR", "VARCHAR2", "VARCHAR", "NVARCHAR2", "NUMBER", "FLOAT", "LONG", "DATE", "TIMESTAMP"]

const SQL_KEYWORDS = ["ADD", "ALL", "ALTER", "ANALYZE", "AND", "AS", "ASC", "BEFORE", "BETWEEN", "BINARY", "BOTH", "BY", "CALL",
	"CASCADE", "CASE", "CHANGE", "CHARACTER", "CHECK", "COLLATE", "COLUMN", "CONDITION", "CONSTRAINT", "CONTINUE", "CREATE", "CROSS", "CURRENT_TIME",
	"CURRENT_USER", "CURSOR", "DATABASE", "DEC", "DECIMAL", "DECLARE", "DEFAULT", "DELETE", "DESC", "DETERMINISTIC", "DISTINCT", "DROP", "EACH", "ELSE",
	"EXISTS", "EXPLAIN", "FALSE", "FETCH", "FOR", "FORCE", "FOREIGN", "FROM", "FULL", "GRANT", "GROUP", "HAVING", "IF", "IGNORE", "IN", "INDEX", "INNER", "INSERT",
	"INTERVAL", "INTO", "IS", "ITERATE", "JOIN", "KEY", "KEYS", "KILL", "LABEL", "LEADING", "LEFT", "LIKE", "LIMIT", "LINEAR", "LOAD", "LOCALTIME", "LOCK", "MATCH",
	"NATURAL", "NOT", "NULL", "NUMERIC", "ON", "OPTIMIZE", "OPTION", "OR", "ORDER", "OUTER", "OVER", "PARTITION", "PRECISION", "PRIMARY", "PROCEDURE", "PURGE", "RANGE",
	"READ", "READS", "REAL", "REFERENCES", "RENAME", "REPEAT", "RESTRICT", "RETURN", "REVOKE", "RIGHT", "ROW_NUMBER", "SCHEMA", "SELECT", "SHOW", "SQL", "TABLE", "THEN",
	"TO", "TRAILING", "TRIGGER", "TRUE", "UNDO", "UNION", "UNION ALL", "UNIQUE", "UNLOCK", "UPDATE", "USAGE", "USE", "USING", "VALUES", "VARYING", "WHEN", "WHERE", "WITH",
	"WRITE"]


/*
  2022-11-23修改
  Oracle改为使用ADB的关键字
  因为Oracle的2000多个关键字会使得编辑器的初始化变得很慢
*/
// import { SQL_KEYWORDS } from "./adb"

export { SQL_KEYWORDS, SQL_DATA_TYPES, SQL_FUNCTION }