#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npm run lint
npm run lint-staged

lint_exit_code=$?

if [ $lint_exit_code -ne 0 ]; then
  echo "Lint failed with exit code $lint_exit_code. Commit aborted."
  exit $lint_exit_code
else
  echo "Lint passed."
fi